Pytorch workflow :

1) Prepare and Load the Data

2) Fitting the model to data

3) Making predictions and evaluating the model

4) Saving and loading a model

5) Putting it all together

In [1]:
import torch
from torch import nn

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
#workflow of LinearRegression

weight = 1
bias = 0.0

start = 2
end = 101
range = 2
X = torch.arange(start,end,range).unsqueeze(dim=1)
y = weight*X+bias

In [4]:
X

tensor([[  2],
        [  4],
        [  6],
        [  8],
        [ 10],
        [ 12],
        [ 14],
        [ 16],
        [ 18],
        [ 20],
        [ 22],
        [ 24],
        [ 26],
        [ 28],
        [ 30],
        [ 32],
        [ 34],
        [ 36],
        [ 38],
        [ 40],
        [ 42],
        [ 44],
        [ 46],
        [ 48],
        [ 50],
        [ 52],
        [ 54],
        [ 56],
        [ 58],
        [ 60],
        [ 62],
        [ 64],
        [ 66],
        [ 68],
        [ 70],
        [ 72],
        [ 74],
        [ 76],
        [ 78],
        [ 80],
        [ 82],
        [ 84],
        [ 86],
        [ 88],
        [ 90],
        [ 92],
        [ 94],
        [ 96],
        [ 98],
        [100]])

In [5]:
y

tensor([[  2.],
        [  4.],
        [  6.],
        [  8.],
        [ 10.],
        [ 12.],
        [ 14.],
        [ 16.],
        [ 18.],
        [ 20.],
        [ 22.],
        [ 24.],
        [ 26.],
        [ 28.],
        [ 30.],
        [ 32.],
        [ 34.],
        [ 36.],
        [ 38.],
        [ 40.],
        [ 42.],
        [ 44.],
        [ 46.],
        [ 48.],
        [ 50.],
        [ 52.],
        [ 54.],
        [ 56.],
        [ 58.],
        [ 60.],
        [ 62.],
        [ 64.],
        [ 66.],
        [ 68.],
        [ 70.],
        [ 72.],
        [ 74.],
        [ 76.],
        [ 78.],
        [ 80.],
        [ 82.],
        [ 84.],
        [ 86.],
        [ 88.],
        [ 90.],
        [ 92.],
        [ 94.],
        [ 96.],
        [ 98.],
        [100.]])

In [6]:
torch.is_tensor(X)

True

In [7]:
len(X)

50

In [8]:
len(y)

50

#Splitting the Data into training , testing

It is always advisory to divide the dataset into 80% for training , 20% for testing

In [9]:
#Create a train\test split
train_split = int(0.80 * len(X))
x_train , y_train = X[:train_split] , y[:train_split]
x_test , y_test = X[train_split:] , y[train_split:]

In [10]:
print(f"x_train : {len(x_train)} , x_test : {len(x_test)} , y_train : {len(y_train)} , y_test : {len(y_test)}")

x_train : 40 , x_test : 10 , y_train : 40 , y_test : 10


What our model does :

* Start with random values (weights & bias)
* Look at training data and adjust the random values to better represent (or get closer to) the ideal values (the weights & bias values we used to create the data)

Through two main algorithms

1) Gradient descent

2) Backpropagation

In [11]:
from torch import nn
#Create a Linear Regression model
#Almost everything inherits from nn.Module

class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(1,requires_grad = True,dtype = torch.float))
    self.bias = nn.Parameter(torch.randn(1,requires_grad = True , dtype = torch.float))
  #Forward method to define the computation in the model
  def forward(self,x : torch.Tensor) -> torch.Tensor :
    return self.weight * x + self.bias


#Pytorch model building esssentials :

* torch.nn -> contains all of the buildings for computational graphs (a neural network can be considered a computational graph)

* torch.nn.Parameter -> What parameters should our model try and learn , often a Pytorch layer from torch.nn will set these for us

* torch.nn.Module -> The base class for all neural network modules , if you subclass it , you should overwrite forward()

* torch.optim -> This where the optimizers in Pytorch live , they will help with gradient descent

* def.forward() -> All nn.Module subclasses require you to overwrite forward() , this method defines what happens in the forward computation

#Checking the contents of our Pytorch model

* We can check our model's parameters or what's inside our model using .parameters()

In [12]:
#Creating a reproducable seed
torch.manual_seed(42)
#Creating a instance of the class
model = LinearRegression()
#Check out the parameters
list(model.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [13]:
 #List the named parameters
 model.state_dict()

OrderedDict([('weight', tensor([0.3367])), ('bias', tensor([0.1288]))])

#Making prediction using 'torch.inference_mode()'

To check our model's predictive power , let's check how well it predicts y_test based on x_test

When we pass data through our model , it's going to run it through the forward() method

In [14]:
#Making predictions
with torch.inference_mode():
  y_pred = model(x_test)
y_pred

tensor([[27.7374],
        [28.4108],
        [29.0842],
        [29.7576],
        [30.4309],
        [31.1043],
        [31.7777],
        [32.4511],
        [33.1245],
        [33.7978]])

In [15]:
y_test

tensor([[ 82.],
        [ 84.],
        [ 86.],
        [ 88.],
        [ 90.],
        [ 92.],
        [ 94.],
        [ 96.],
        [ 98.],
        [100.]])

Our model didn't perform well here because we had initialised random parameter

#Train Model

• Loss function: A function to measure how wrong your model's predictions are to the ideal outputs, lower is better.


• Optimizer: Takes into account the loss of a model and adjusts the model's parameters (e.g. weight & bias in our case) to improve the loss
function.


And specifically for PyTorch, we need:

A training loop

A testing loop

In [16]:
#loss func

loss_fn = nn.L1Loss()

#optimizer func

Optimizer = torch.optim.SGD(model.parameters() , lr = 0.001)

#Building a training loop and testing loop in Pytorch

1.Loop through the data

2.Forward pass (this involves data moving through our model's forward() functions) to make predictions on propagation

3.Calculate the loss(compare forward pass predictions to ground truth labels)

4.Optimizer zero grad

5.Loss backward - moves backwards through the network to calculate the gradients of each of the parameters of the loss (backpropagation)

6.Optimzer step - use the optimizer to adjust our model's parameters to try and improve the loss (gradient descent)

In [17]:
torch.manual_seed(42)
from builtins import range
#1.Loop through the data
epochs = 100
for epoch in range(epochs):
  #Set the model to training mode

  model.train() #Train mode in Pytorch sets all parameters that require gradients to require gradients

  #2.Forward pass

  y_pred = model(x_train)

  #3.Loss

  Loss = loss_fn(y_pred , y_train)
  print(f"Loss is {Loss}")

  #4.Optimizer

  Optimizer.zero_grad()

  #5.Perform backpropagation on the loss with respect to the parameters of the model

  Loss.backward()


  #6.Step the optimzer(performs gradient descent)

  Optimizer.step()

  ##Testing
  model.eval()
print(f"Loss is {Loss}")
print(f" model.Parameter {model.state_dict()}")

Loss is 27.066884994506836
Loss is 25.3848876953125
Loss is 23.702884674072266
Loss is 22.020885467529297
Loss is 20.338886260986328
Loss is 18.656885147094727
Loss is 16.974884033203125
Loss is 15.292881965637207
Loss is 13.610880851745605
Loss is 11.928881645202637
Loss is 10.246881484985352
Loss is 8.564882278442383
Loss is 6.882882595062256
Loss is 5.2008819580078125
Loss is 3.5188801288604736
Loss is 1.839240312576294
Loss is 0.1908290684223175
Loss is 1.3380210399627686
Loss is 0.36226189136505127
Loss is 1.2516213655471802
Loss is 0.44536709785461426
Loss is 1.1898715496063232
Loss is 0.5053712129592896
Loss is 1.1486690044403076
Loss is 0.5455338358879089
Loss is 1.107466459274292
Loss is 0.585695743560791
Loss is 1.066265344619751
Loss is 0.6261041760444641
Loss is 1.0415161848068237
Loss is 0.6504693031311035
Loss is 1.016767144203186
Loss is 0.6748364567756653
Loss is 0.9920177459716797
Loss is 0.6992042064666748
Loss is 0.9672685861587524
Loss is 0.7235697507858276
Loss is 

In [18]:
Loss

tensor(0.5087, grad_fn=<MeanBackward0>)